name: Test

on:
  push:
    branches:
      - main
      - test**

jobs:
  test-events:
    runs-on: ubuntu-latest
    
    steps:
      - namee: Visible Step
        run: |
          echo "Running dispatch trigger..."
          curl --version  # or even just this will show up
          
