AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation Template to create an S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucet-ani-001-test-useasttemp01
